//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCityEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adm_ForecastWeather
    {
        public long IDForecastWeather { get; set; }
        public int IDStation { get; set; }
        public int MinTemp { get; set; }
        public int MaxTemp { get; set; }
        public int RainFall { get; set; }
    }
}
